apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendations-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendations
  template:
    metadata:
      labels:
        app: recommendations
    spec:
      containers:
        - name: recommendations
          image: anivone/recommendations-service
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: consultation-platform
            - name: MONGO_URI
              value: "mongodb://recommendations-mongo-srv:27017/recommendations-service"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: recommendations-srv
spec:
  selector:
    app: recommendations
  type: ClusterIP
  ports:
    - name: recommendations
      protocol: TCP
      port: 3000
      targetPort: 3000
