apiVersion: apps/v1
kind: Deployment
metadata:
  name: specialties-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: specialties
  template:
    metadata:
      labels:
        app: specialties
    spec:
      containers:
        - name: specialties
          image: anivone/specialties-service
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: consultation-platform
            - name: MONGO_URI
              value: "mongodb://specialties-mongo-srv:27017/specialties-service"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: specialties-srv
spec:
  selector:
    app: specialties
  type: ClusterIP
  ports:
    - name: specialties
      protocol: TCP
      port: 3000
      targetPort: 3000
